Время разбивать камни
htmlacademy-ecmascript/2058669-big-trip-simple-19 pull request #3
Opened 2022-12-09 19:12 UTC by CorisMorri

2022-12-10 17:57 UTC, 0snilcy requested changes

2022-12-10 17:57 UTC, 0snilcy commented on src/presenter/board-presenter.js
> +export default class BoardPresenter {
Не совсем подходящее название **Board**

2022-12-10 17:57 UTC, 0snilcy commented on src/presenter/board-presenter.js
> +//import AddNewPointWithoutDestinationsView from '../view/add-new-point-without-destination-view.js';
Не стоит такое в ПР закидывать

2022-12-10 17:57 UTC, 0snilcy commented on src/presenter/board-presenter.js
> +  ListComponent = new ListView();
Почему компоненты в разных регистрах называны?

2022-12-10 17:57 UTC, 0snilcy commented on src/view/add-new-point-view.js
> +function createAddNewPointTemplate() {
А чего не вынес в разные компоненты?

2022-12-16 11:17 UTC, azbykov approved these changes

2022-12-16 11:17 UTC, merged